version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "pnpm run start"
    depends_on:
      - dashboard-db
    networks:
      - dashboard-network

  dashboard-db:
    image: 'bitnami/postgresql'
    container_name: dashboard-db
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=dashboard
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - dashboard-network

volumes:
  postgresql_data:
    driver: local

networks:
  dashboard-network:
